add_rules("mode.release")
add_cxxflags("-fno-exceptions", "-fno-rtti", "-ffreestanding", "-mcpu=arm920t", "-nostdlib")
add_ldflags("-nostdlib")
set_policy("build.optimization.lto", true)
set_languages("cxx23")
set_arch("arm")
set_plat("cross")
add_rules("plugin.compile_commands.autoupdate", {outputdir = "build"})
target("kernel")
  set_kind("binary")
  add_files("kernel.lds")
  add_files("src/main.cpp")
  add_files("src/start.s")
